name: Run build test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DPDK_PATH: dpdk-stable-19.11.12
  DPDK_ARCHIVE: dpdk-19.11.12.tar.xz

jobs:
   build-test:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc make meson ninja-build

    - name: Cache DPDK
      id: cache-dpdk
      uses: actions/cache@v3
      with:
        path: ${{ env.DPDK_PATH }}
        key: ${{ runner.os }}-dpdk-19.11.12

    - name: Build DPDK
      if: steps.cache-dpdk.outputs.cache-hit != 'true'
      run: |
        wget http://fast.dpdk.org/rel/${{ env.DPDK_ARCHIVE }}
        tar xvf ${{ env.DPDK_ARCHIVE }}
        cd ${{ env.DPDK_PATH }}
        meson build
        ninja -C build

    - name: Install DPDK
      run: |
        cd ${{ env.DPDK_PATH }}/build && sudo ninja install

    - name: Set DPDK lib path
      run: |
        export LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu:$(LD_LIBRARY_PATH)

    - name: Build Oceanus
      run: |
        cd app && make -j4
